apiVersion: v1
kind: Service
metadata:
  name: iris-ml-svc
  labels:
    app: iris-ml
spec:
  type: NodePort
  selector:
    app: iris-ml
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
